export { default as Customers } from './Customers'
export { default as Dashboard } from './Dashboard'
export { default as Orders } from './Orders'
export { default as Transaction } from './Transaction'
export { default as Login } from './Login'
export { default as Register} from './Register'
export { default as SparkLine} from './Charts/SparkLine'
export { default as Products} from './Products'
export { default as ProductsBody } from './ProductsBody'
export { default as Profile} from './Profile'
export { default as AddProduct } from './AddProduct'
export { default as Stocks } from './Stocks'
export { default as StocksBody } from './StocksBody'