export { default as Customers } from './Customers'
export { default as Dashboard } from './Dashboard'
export { default as Orders } from './Orders'
export { default as Transaction } from './Transaction'
export { default as Login } from './Login'
export { default as Register} from './Register'
export { default as SparkLine} from './Charts/SparkLine'
export { default as Products} from './Products'
export { default as Tablebody } from './Tablebody'
export { default as Profile} from './Profile'